apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: master-00
    spec:
      containers:
        - name: kubernetes-host
          image: gcr.io/kubeadm/ci-xenial-systemd:test-master-cea375c06ac6cd5741beb9cf96f94063b24e6091-29
          securityContext:
            privileged: true
  - apiVersion: v1
    kind: Pod
    metadata:
      name: node-01
    spec:
      containers:
        - name: kubernetes-host
          image: gcr.io/kubeadm/ci-xenial-systemd:test-master-cea375c06ac6cd5741beb9cf96f94063b24e6091-29
          securityContext:
            privileged: true
  - apiVersion: v1
    kind: Pod
    metadata:
      name: node-02
    spec:
      containers:
        - name: kubernetes-host
          image: gcr.io/kubeadm/ci-xenial-systemd:test-master-cea375c06ac6cd5741beb9cf96f94063b24e6091-29
          securityContext:
            privileged: true
